### PR TITLE
Optimize loading animation

### PR DESCRIPTION
**Pull request by setaman**

### CODE REVIEW

**Comment by HA-NA123** [comment]
is there any call back when the animation end.

**Comment by HA-NA123** [comment]
suppose we display the loader for 10 sec after that callback function will be call.

**Comment by HA-NA123** [comment]
some thing like that when we click on button the loader is stop and then resume again.

**Comment by setaman** [comment]
hey @HA-NA123.  There are no callbacks and no events. All states are controlled externally by props. The component has no hidden states. For example, the component is in loading state as long as `:loading="true"`  is. So you know that loading is complete when `loading` is set to `false`. And you can change this prop as you like, on button click or whatever else.

Do you have a specific use case where you would certainly need some kind of callbacks or events for state changes?

**Pull request merged**
